version: '3.8'

services:
  db:
    build:
      context: ./docker/database
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_DB: tech_tales
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
